### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by min-n** [MarcYu0303/Trans-HADR#1]
I greatly appreciate your outstanding contributions. While attempting to reproduce the code, I encountered an error: "No module named 'graspnet'." I reviewed the related article, which mentions that the pre-trained GraspNet baseline is used to generate 6-DoF grasp poses. However, I was unable to find the utils.py and sample.py files in the provided code.

Could you kindly provide the code for the GraspNet module? I would be very grateful for your assistance.

Thank you very much!

**Comment by MarcYu0303** [comment]
Hi min-n, thank you for pointing out this issue. Since this repo mainly focuses on the Trans_HADR algorithm, I have removed the graspnet module for generating grasps for handover. I have corrected this issue by removing a visualization function "draw_scene_with_open3d" which will not be used in this code. If you are interested in how to generate grasps based on the restored point cloud, please refer to [graspnet-baseline](https://github.com/graspnet/graspnet-baseline) which is used in this project.  You will find it will be easy to implement graspnet on our restored point cloud. If you have any other problems, feel free to ask me 😀

**Comment by min-n** [comment]
> Hi min-n, thank you for pointing out this issue. Since this repo mainly focuses on the Trans_HADR algorithm, I have removed the graspnet module for generating grasps for handover. I have corrected this issue by removing a visualization function "draw_scene_with_open3d" which will not be used in this code. If you are interested in how to generate grasps based on the restored point cloud, please refer to [graspnet-baseline](https://github.com/graspnet/graspnet-baseline) which is used in this project. You will find it will be easy to implement graspnet on our restored point cloud. If you have any other problems, feel free to ask me 😀

okok,Thank you for your prompt response. I have a small question regarding the YAML files. In train_hadr.yaml, it specifies SWIN:PRETRAIN_CKPT: 'path/to/swin_pretrain.pth', while in test_hadr.yaml, it specifies SWIN:PRETRAIN_CKPT: '/home/yuran/Projects/HandDepth/pretrained_model/swin_tiny_patch4_window7_224.pth'.

I would like to know if both SWIN:PRETRAIN_CKPT entries in these YAML files are referring to the same file, swin_tiny_patch4_window7_224.pth.
Thank you!😀😀😀

**Comment by MarcYu0303** [comment]
yes, both of them refer to the pre-trained Swin transformer weight. I will upload it together with the data.

**Comment by min-n** [comment]
> yes, both of them refer to the pre-trained Swin transformer weight. I will upload it together with the data.

Upload? When will it be uploaded? By the way, while reproducing the code, I noticed that both train_hadr.yaml and test_hadr.yaml specify trainer_name: lidf, but there is no train_lidf.py file in the trainers folder—only train_hadr.py and train_keypoints.py. Should the trainer_name be changed to hadr?

**Comment by MarcYu0303** [comment]
I have upload it together with the Trans-Hand dataset. For the trainer_name question, I have correct this code.

**Comment by min-n** [comment]
> I have upload it together with the Trans-Hand dataset. For the trainer_name question, I have correct this code.

okok.Thank you very much for your prompt response!😀

**Comment by min-n** [comment]
I encountered another issue while running `bash scripts/train_hadr.sh`, which shows the error: "Error during single process training: module 'constant' has no attribute 'XMIN'." I would like to ask if `XMIN` and `XMAX` are custom-defined constants?

**Comment by MarcYu0303** [comment]
Hi, min-n, sorry for my late reply. I have uploaded the constant parameters in this repo, and maybe you can pull it again to see if it solves your question. Since this work is still under review, I will temporarily close the access to the dataset. If you need it, you can email me to get an early access. Sorry again for the inconvenience to you.

**Comment by min-n** [comment]
Hello, MarcYu0303, I see that the modifications have been made. Thank you very much for your reply. I have already downloaded the dataset. 😀

**Comment by MarcYu0303** [comment]
Cool, you can feel free to try it and please do not spread it since this work has not been accepted yet. If you encounter any other problems, please ask me here! Thanks again for your interest!

**Comment by min-n** [comment]
Okay, no problem!
